### ISSUE TITLE
 Make separate mesh-create_ap.sh script to handle accesspoint setup and remove duplicate script code from 11s/adhoc scripts.

### ISSUE THREAD

**Issue by mbaddeley** [tiiuae/mesh_com#49] opened 2021-06-09 06:17 UTC
There is some existing code around this in mesh-tb/sc-mesh-secure-deployment module in configure.sh + creation of mesh-ap@.service.

**Comment by joenpera** [comment] 2021-06-14 05:52
Just adding reminder, that this also affects to fogsw systemd delivery.

**Comment by mbaddeley** [comment] 2021-07-26 05:38
@joenpera will this not be closed by mesh-11sh-mr.sh in #70?

**Comment by joenpera** [comment] 2021-07-26 06:42
No.  mesh-11s-mr.sh is a duplicate to mesh-11s.sh and mesh-11s.sh can be removed when mr-code is in use for 11s.   I think we need to have ap code in place for debug purposes anyway.  We can't use mesh-ap.sh for mesh_com ROS node (compare to create_ap()-function in mesh-11s-mr.sh).

**Comment by mbaddeley** [comment] 2021-11-02 06:15
Is this closed now? Pretty sure this has been fixed by something.

**Comment by joenpera** [comment] 2021-11-02 06:39
Currently mesh-11s.sh is used for AP setup also. In this (fogsw) case AP setup has been debug purposes only.  This is not a bug, but enhancement.  I think we can close this one.  I know that things will change a lot with coming mesh 1.x implementations when taken in use.

**Comment by DamienDeMayaTII** [comment] 2024-02-19 09:46
Not relevant anymore. Also issues are tracked in Jira.

**Closed by DamienDeMayaTII** 2024-02-19 09:46 UTC
Labels: enhancement
